### PR TITLE
minimal changes to compatibility with OpenFOAM-v2406

### PR DESCRIPTION
**Pull request by akdemironur**

### CODE REVIEW

**Comment by TonkomoLLC** [comment]
Thank you for this contribution. As far as I can tell the only changes to v1806-v2212 code is in solveFluid.H and solveSolid.H for the transient solver? Thanks for confirming.

I did some checking and found that these changes are also needed for v2312, and the v1806 solver seems to still work for v2306.

**Comment by akdemironur** [comment]
Yes, the only changes are these lines:

- `mesh.data::add("finalIteration", true);` 
- `mesh.data::add("finalIteration", false);`

converted to:

- `mesh.data().setFinalIteration(true);` 
- `mesh.data().setFinalIteration(false);`

in both `solveFluid.H` and `solveSolid.H`.

Actually, I don’t know if additional changes are needed, but this compiles, and I am able to solve `counterFlowFlame2D` in the tutorials. I also obtained the same results as in `v2206`.

**Comment by TonkomoLLC** [comment]
Perfect! Thank you very much for the contribution!!

**Comment by TonkomoLLC** [comment]
I ended up renaming the directory to reflect it also compiles with v2312.  Thanks again !

**Pull request merged**
